### ISSUE TITLE
Hangs at Exporting (pdf) ...

### ISSUE THREAD

**Issue by rscarson** [djfdyuruiry/pretty-markdown-pdf#21]
Trying to run an export with the following configuration: 
```
{
	"executablePath": "/c/Program Files/Google/Chrome/Application/chrome.exe"
}
```

With `pretty-md-pdf -i test.md -c <config path>`

I am on ubuntu, through the WSL on Windows 10.

Export hands indefinitely on:
```
[pretty-md-pdf] Exporting (pdf) ...
```

Other export types hang the same way

**Comment by djfdyuruiry** [comment]
Hi @rscarson 

I have not tested this under WSL - what Ubuntu version are you running there?

**Comment by rscarson** [comment]
I am running Ubuntu 18.04.2 LTS

**Comment by djfdyuruiry** [comment]
Looks like this is due to Puppeter issue with WSL/WSL 2 https://github.com/puppeteer/puppeteer/issues/1837 

Might be a workaround that can be used and enabled with a config flag - will need to see, any input welcome

**Comment by rscarson** [comment]
Passing '--disable-gpu', '--no-sandbox' to google chrome might be a workaround, according to that link

**Comment by djfdyuruiry** [comment]
Would you be able to test this by using the `--chromium-args` command line options - this supports a JSON array:

```bash
pretty-md-pdf -i "test.md" -c "<config path>" --chromium-args '[ "--disable-gpu", "--no-sandbox" ]'
```

**Comment by rscarson** [comment]
It now vomits a series of errors before hanging:

```
[pretty-md-pdf] Converting markdown file: manual.md
[pretty-md-pdf] Converting (convertMarkdownToHtml) ...
[pretty-md-pdf] Exporting (pdf) ...
ERROR: page.goto()
ERROR: page.goto()
Error: net::ERR_FILE_NOT_FOUND at file:///c/<...>/documentation/manual_tmp.html
Error: net::ERR_FILE_NOT_FOUND at file:///c/<...>/documentation/manual_tmp.html
    at navigate (/usr/lib/node_modules/pretty-markdown-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/usr/lib/node_modules/pretty-markdown-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/lib/node_modules/pretty-markdown-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:16)
    at async Page.goto (/usr/lib/node_modules/pretty-markdown-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:819:16)
    at async exportPdf (/usr/lib/node_modules/pretty-markdown-pdf/markdown-pdf.js:301:5)
    at async Object.convertMarkdown (/usr/lib/node_modules/pretty-markdown-pdf/markdown-pdf.js:50:11)
    at async Object.convertMd (/usr/lib/node_modules/pretty-markdown-pdf/index.js:41:9)
    at async main (/usr/lib/node_modules/pretty-markdown-pdf/bin/pretty-md-pdf.js:77:5)
ERROR: exportPdf()
ERROR: exportPdf()
TypeError: Cannot read property 'top' of undefined
TypeError: Cannot read property 'top' of undefined
    at exportPdf (/usr/lib/node_modules/pretty-markdown-pdf/markdown-pdf.js:335:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.convertMarkdown (/usr/lib/node_modules/pretty-markdown-pdf/markdown-pdf.js:50:11)
    at async Object.convertMd (/usr/lib/node_modules/pretty-markdown-pdf/index.js:41:9)
    at async main (/usr/lib/node_modules/pretty-markdown-pdf/bin/pretty-md-pdf.js:77:5)
```

Note that the manual_tmp.html file it cannot find does in fact exist - it creates one in the directory

**Comment by djfdyuruiry** [comment]
Closing due to inactivity
